[package]
name = "demo-python-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "demo_python_api"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.3", features = ["extension-module","anyhow", "abi3-py38"] }
pyo3-log = "0.6"
numpy="0.16.2"
log= "0.4.17"
anyhow="1.0.57"
parking_lot= "0.12.1"

[build-dependencies]
bindgen = "0.59.2"
cmake = "0.1"
