name: Build

on:
    push:
        branches:
            - main

jobs:
    build:
        strategy:
            matrix:
                platform: [windows-latest, macos-latest, ubuntu-latest]

        runs-on: ${{matrix.platform}}
        steps:
            - name: Enable long paths
              run: |
                  New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
              shell: pwsh

            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: messense/maturin-action@v1
              with:
                  command: build
                  args: --release -o dist --universal2
            - name: Upload wheels
              uses: actions/upload-artifact@v3
              with:
                  name: ${{matrix.platform}} wheels
                  path: dist
