name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build
        uses: messense/maturin-action@v1
        with:
          command: build
          args: --release -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.platform}} wheels
          path: dist
