name: Build

on:
  push:
    branches:
      - main
  pull_request: # TODO (aliddell): remove before merge
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build (macOS)
        if: matrix.platform == 'macos-latest'
        uses: messense/maturin-action@v1
        with:
          command: build
          target: universal2-apple-darwin
          args: --release -o dist

      - name: Build
        if: matrix.platform != 'macos-latest'
        uses: messense/maturin-action@v1
        with:
          command: build
          args: --release -o dist

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.platform}} wheels
          path: dist
