name: Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: ${{ matrix.platform }} ${{ matrix.python }} ${{ matrix.toxenv }}
        runs-on: ${{ matrix.platform }}
        strategy:
            fail-fast: false
            matrix:
                platform: ["windows-latest", "macos-latest"]
                python: ["3.8", "3.9", "3.10"]
                exclude:
                    - platform: macos-latest
                      python: "3.8"
                    - platform: macos-latest
                      python: "3.9"

        permissions:
            actions: write
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.10.0
              with:
                  access_token: ${{ github.token }}

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT }}
                  submodules: recursive

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}

            - name: Install
              run: |
                  pip install --upgrade pip
                  pip install -e .[testing]

            - name: Test
              run: |
                  python -m pytest --color=yes --cov-report=xml --cov=calliphlox --maxfail=5
