name: Test DCAM

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: [self-hosted,dcam]
        timeout-minutes: 20
        strategy:
            fail-fast: false
            matrix:
                python: ["3.8", "3.9", "3.10"]

        permissions:
            actions: write
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT }}
                  submodules: recursive

            - name: Get CMake 3.24
              uses: lukka/get-cmake@latest
              with:
                cmakeVersion: 3.24.3

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Install
              run: |
                  pip install --upgrade pip
                  pip install -e .[testing]

            - name: Test
              run: |
                  python -m pytest -k test_dcam --color=yes --cov-report=xml --cov=acquire --maxfail=5 --log-cli-level=0
